### ISSUE TITLE
Directory to clone industrial_ci into already exists in gitlab-ci

### ISSUE THREAD

**Issue by miguelprada** [ros-industrial/industrial_ci#186]
I'm attempting to configure `industrial_ci` in a GitLab hosted project and I'm encountering some problems with the default `.gitlab-ci.yml` provided as an example.

I'm using the docker executor, and the problem I have is that if I clone `industrial_ci` as suggested in that config file, i.e. cloning into parent folder with

`git clone https://github.com/ros-industrial/industrial_ci ../.ci_config` 

then the build container complains that the directory already exists:

```
...
$ git clone https://github.com/ros-industrial/industrial_ci ../.ci_config
fatal: destination path '../.ci_config' already exists and is not an empty directory.
ERROR: Job failed: exit code 128
```

I guess the gitlab runner is mounting some volumes from the runner itself into the executor, and therefore the `../.ci_config` directory exists from previous jobs. In fact, by changing to some other path, the job succeeds on the first attempt but then fails in every subsequent one.

I can see that this path was introduced in #185 to fix the tests for `industrial_ci` itself, avoiding duplicate `industrial_ci` copies in the source directory, but I think that it is breaking the `for reguar users` use-case.

**Comment by ipa-mdl** [comment]
Could you provide us (parts of) your config?
I can't imagine any reason why this folder should already exist.

**Comment by ipa-mdl** [comment]
So it works for the shared runners at gitlab.com: https://gitlab.com/ipa-mdl/ci-example/pipelines
But I can confirm this problem with my local gitlab instance with a docker-based runner.

**Comment by miguelprada** [comment]
This is my `.gitlab-ci.yaml`:

```yaml
image: docker:git # docker and git clients

services:
  - docker:dind # enable docker-in-docker

before_script:
  - apk add --update bash coreutils # install industrial_ci dependencies
  - git clone https://github.com/ros-industrial/industrial_ci ../.ci_config

indigo:
  script: ../.ci_config/gitlab.sh
  variables:
    ROS_DISTRO: "indigo"
    UPSTREAM_WORKSPACE: "file"
    ROSINSTALL_FILENAME: ".rosinstall"
    ROS_PARALLEL_JOBS: "-j1"
```

I'm running the gitlab runner as a docker image following [these instructions](https://docs.gitlab.com/runner/install/docker.html), and configured it as as project specific, and to use docker-based executors. The runner config is:

```
concurrent = 1
check_interval = 0

[[runners]]
  name = "roboticsrunner"
  url = <COMPANY_HOSTED_GITLAB_SERVER>
  token = <PROJECT_TOKEN>
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "docker:git"
    privileged = true
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
  [runners.cache]
```
