### ISSUE TITLE
`catkin_test_results --verbose` explodes travis log beyond max

### ISSUE THREAD

**Issue by ipa-fxm** [ros-industrial/industrial_ci#253]
with the changes introduced in #251 (related to #118), our Travis jobs began to fail due to exceeding log length maximum (we haven't seen this earlier due to other Travis/Docker issues - see #247 #248)

```
The log length has exceeded the limit of 4 MB (this usually means that the test suite is raising the same exception over and over).

The job has been terminated
```

I can ensure that "the test suite is raising the same exception over and over" is **not** true in our case!

To give some numbers:
 - all CI steps from start to build-step produce about 2000 lines of output
 - the test-step (--verbose) produces more than 8000 lines of output....

Is there a way to fix #118 without using `--verbose` during the test-step?

Our `travis.yml` looks pretty standard (and has worked before):
```
sudo: required
dist: trusty
language: generic
notifications:
  email:
    on_success: change
    on_failure: always
env:
  global:
    - ROS_REPO=ros
    - NOT_TEST_INSTALL=true
  matrix:
    - ROS_DISTRO=indigo UPSTREAM_WORKSPACE=file
    - ROS_DISTRO=indigo UPSTREAM_WORKSPACE=file $ROSINSTALL_FILENAME="custom.rosinstall"
    - ROS_DISTRO=kinetic UPSTREAM_WORKSPACE=file
matrix:
  allow_failures:
    - env: ROS_DISTRO=kinetic UPSTREAM_WORKSPACE=file
install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  - .ci_config/travis.sh
#  - ./travis.sh  # Enable this when you have a package-local script 
```
