### ISSUE TITLE
gitlab runner hangs on wstool merge

### ISSUE THREAD

**Issue by ipa-fez** [ros-industrial/industrial_ci#295]
Job output:

```
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
Function setup_rosdep returned with code '0' after 0 min 16 sec 
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
Writing /root/catkin_ws/src/.rosinstall

update complete.

     Change details of element (Use --merge-keep or --merge-replace to change):
  repo_1

     Add new elements:
  repo_2,  repo_3,  repo_4

Continue: (y)es, (n)o, (v)erbosity, (a)dvanced options: 
```

It waits for input at this point until the job times out.

Our .gitlab-ci.yaml:

```
image: docker:git # docker and git clients

variables:
  TMPDIR: "${CI_PROJECT_DIR}.tmp" #
  DOCKER_DRIVER: "overlay2" # recommended for docker-in-docker, needs overlay kernel module loaded on host

# enable docker-in-docker
services:
  - docker:dind

before_script:
  - apk add --update bash coreutils tar # install industrial_ci dependencies
  - git clone https://github.com/ros-industrial/industrial_ci .ci_config

# setup the actual tests

kinetic:
  script: .ci_config/gitlab.sh
  variables:
    ROS_DISTRO: "kinetic"
    UPSTREAM_WORKSPACE: "file"
```

This is currently happening on a merge-request. Restarting the job does not resolve the issue. The master branch was building fine, but there it has all repos in the "Add new elements" line.

Another difference seems to be that the merge request output starts with "Cloning repository..." while the master branch says "Fetching changes" instead.

A workaround could be adding a `-y` flag to the `wstool merge`.
