### ISSUE TITLE
Alternative setup without submodules

### ISSUE THREAD

**Issue by ipa-mdl** [ros-industrial/industrial_ci#3]
git submodules are a little bit cumbersome to use, especially to keep track with update.

For an easier maintenance it should be sufficient to have a client script like this:
```YAML
install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  - source .ci_config/travis.sh
  # - source ./travis.sh
```

I will try both variants with ros_canopen.
