### ISSUE TITLE
ROS2 support 

### ISSUE THREAD

**Issue by ipa-jba** [ros-industrial/industrial_ci#333]
Do you have any plans to make industrial_ci available for ROS2 (maybe related to #301)

**Comment by ipa-mdl** [comment]
No actual plan yet.
I would be in favor of a colcon-based rewrite, perhaps in Python.

**Comment by ipa-mdl** [comment]
I have now created a project: https://github.com/ros-industrial/industrial_ci/projects/1
For simplicity, the current version should be refactored first.

**Comment by AustinDeric** [comment]
I use this script for ROS2 CI: https://github.com/AustinDeric/control_msgs/blob/bouncy-devel/.travis.yml
```
ervices:
  - docker

script:
- docker run --name build-container -dit osrf/ros2:bouncy-ros-base /bin/bash
- docker exec build-container /bin/bash -c 'mkdir -p /ros2_ws/src'
- docker exec build-container /bin/bash -c 'apt update && apt install -y python3-colcon-common-extensions python-rosdep && rosdep init && rosdep update'
- docker cp $TRAVIS_BUILD_DIR build-container:/ros2_ws/src/
- docker exec build-container /bin/bash -c 'source /opt/ros/bouncy/setup.bash && cd /ros2_ws/ && rosdep install --from-paths src --ignore-src --rosdistro bouncy -r -y'
- docker exec build-container /bin/bash -c 'source /opt/ros/bouncy/setup.bash && cd /ros2_ws/ && colcon build --symlink-install'
```
It works well:
https://travis-ci.org/AustinDeric/control_msgs/jobs/462963429

There is also a gitlab version that produces a  dockerfile:
https://github.com/AustinDeric/control_msgs/blob/bouncy-devel/.gitlab-ci.yml
```
image: docker:git
services:
  - docker:dind
variables:
  ENV_IMAGE: osrf/ros2:bouncy-ros-base
  BUILD_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
stages:
  - build

build:
  stage: build
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker run --name build-container -dit $ENV_IMAGE /bin/bash
    - docker exec build-container /bin/bash -c 'mkdir -p /ros2_ws/src'
    - docker exec build-container /bin/bash -c 'apt update && apt install -y python3-colcon-common-extensions python-rosdep && rosdep init && rosdep update'
    - docker cp $CI_PROJECT_DIR build-container:/ros2_ws/src/
    - docker exec -w /ros2_ws build-container /bin/bash -c 'source /opt/ros/bouncy/setup.bash && rosdep install --from-paths src --ignore-src --rosdistro bouncy -r -y'
    - docker exec -w /ros2_ws build-container /bin/bash -c 'source /opt/ros/bouncy/setup.bash && colcon build --symlink-install'
    - docker commit build-container $BUILD_IMAGE
    - docker push $BUILD_IMAGE
```

I think industrial CI might want to leverage this approach.  Food for thought. I can submit an PR if interested?
