### ISSUE TITLE
Setup gitlab ci failed on apk

### ISSUE THREAD

**Issue by manhha1402** [ros-industrial/industrial_ci#367]
Hi,
I am very new to CI. I want to set up my CI for my gitlab repo. Here is .gitlab-ci.yaml:

```yaml
image: docker:git
services:
  - docker:dind
before_script:
  - apk add --update bash coreutils tar
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci .industrial_ci
kinetic:
  script: .industrial_ci/gitlab.sh ROS_DISTRO=kinetic
```
Error:
```
$ apk add --update bash coreutils tar
bash: line 78: apk: command not found
```

Do you have any idea why it is failing?
Thanks
