### ISSUE TITLE
Have rosinstall use self-signed certificate

### ISSUE THREAD

**Issue by kjeremy** [ros-industrial/industrial_ci#376]
My repo `ros_pkg_b` depends on `ros_pkg_a` which I have specified in my `.rosinstall` file:

```yaml
- git:
    local-name: pkg_a
    uri: https://ago-git.us.ara.com/jkolb/ros_pkg_a.git
    version: master
```

That git repo uses a self-signed cert and during build I get:

> >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
> Starting function 'setup_rosws'
> Writing /root/catkin_ws/src/.rosinstall
> 
> update complete.
>      Performing actions: 
> 
>      Add new elements:
>   pkg_a
> 
> Config changed, maybe you need run wstool update to update SCM entries.
> Overwriting /root/catkin_ws/src/.rosinstall
> 
> update complete.
> HOSTNAME=f87373937503
> OS_NAME=ubuntu
> TARGET_REPO_PATH=/root/src/ros_pkg_b
> TERM=dumb
> ROS_ROOT=/opt/ros/kinetic/share/ros
> OS_CODE_NAME=xenial
> ROS_PACKAGE_PATH=/opt/ros/kinetic/share
> ROS_MASTER_URI=http://localhost:11311
> ROSINSTALL_FILENAME=.rosinstall
> ROS_VERSION=1
> LC_ALL=C.UTF-8
> ICI_SRC_PATH=/root/ici
> LD_LIBRARY_PATH=/opt/ros/kinetic/lib
> CATKIN_PARALLEL_TEST_JOBS=-p4
> APTKEY_STORE_SKS=hkp://ha.pool.sks-keyservers.net
> IN_DOCKER=true
> PATH=/opt/ros/kinetic/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
> ROS_PARALLEL_JOBS=-j8
> UPSTREAM_WORKSPACE=file
> _DO_NOT_FOLD=true
> TARGET_REPO_NAME=ros_pkg_b
> PWD=/
> ROS_PARALLEL_TEST_JOBS=-j8
> LANG=C.UTF-8
> HASHKEY_SKS=0xB01FA116
> ROSLISP_PACKAGE_DIRECTORIES=
> DOCKER_BASE_IMAGE=ubuntu:xenial
> APTKEY_STORE_HTTPS=https://raw.githubusercontent.com/ros/rosdistro/master/ros.key
> HOME=/root
> SHLVL=1
> ROS_DISTRO=kinetic
> CATKIN_WORKSPACE=/root/catkin_ws
> PYTHONPATH=/opt/ros/kinetic/lib/python2.7/dist-packages
> PKG_CONFIG_PATH=/opt/ros/kinetic/lib/pkgconfig
> CMAKE_PREFIX_PATH=/opt/ros/kinetic
> CATKIN_PARALLEL_JOBS=-p4
> ROS_ETC_DIR=/opt/ros/kinetic/etc/ros
> _=/usr/bin/env
> [pkg_a] Fetching https://ago-git.us.ara.com/jkolb/ros_pkg_a.git (version master) to /root/catkin_ws/src/pkg_a
> Cloning into '/root/catkin_ws/src/pkg_a'...
> fatal: unable to access 'https://ago-git.us.ara.com/jkolb/ros_pkg_a.git/': server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
> Exception caught during install: Error processing 'pkg_a' : [pkg_a] Checkout of https://ago-git.us.ara.com/jkolb/ros_pkg_a.git version master into /root/catkin_ws/src/pkg_a failed.
> 
> ERROR in config: Error processing 'pkg_a' : [pkg_a] Checkout of https://ago-git.us.ara.com/jkolb/ros_pkg_a.git version master into /root/catkin_ws/src/pkg_a failed.
> 
> <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
> Function 'setup_rosws' returned with code '1' after 0 min 0 sec

My gitlab-runner specifies the correct crt file in it's config:

```ini
[[runners]]
  name = "jkolb-multi-ros-test"
  url = "https://ago-git.us.ara.com"
  token = "CZb36Udqn8J_zK1Jk_CS"
  tls-ca-file = "/etc/gitlab-runner/certs/ago-git.us.ara.com.crt"
  executor = "docker"
  [runners.custom_build_dir]
  [runners.docker]
    tls_verify = false
    image = "docker:git"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
```

but that doesn't seem to make it down.

**Comment by ipa-mdl** [comment]
This is not yet implemented..
The CA key might get exposed in `CI_SERVER_TLS_CA_FILE`.
Please try setting
```
DOCKER_RUN_OPTS="-v '$CI_SERVER_TLS_CA_FILE:$CI_SERVER_TLS_CA_FILE' -e '$GIT_SSL_CAPATH=$CI_SERVER_TLS_CA_FILE'
```

Please check (with `env`) if `GIT_SSL_CAPATH` gets set by Gitlab.
If this is they case, you can even set
```
DOCKER_RUN_OPTS="-v '$GIT_SSL_CAPATH:$GIT_SSL_CAPATH' -e GIT_SSL_CAPATH
```

(There might be some issues with the quotes..)

If you find a solution, we can prepare a patch  that sets this for all Gitlab CI instances :)

**Comment by kjeremy** [comment]
Using:

```yaml
image: docker:git
services:
  - docker:dind
before_script:
  - apk add --update bash coreutils tar
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci .industrial_ci
kinetic:
  script:
    - env
    - .industrial_ci/gitlab.sh DOCKER_RUN_OPTS="-v '$CI_SERVER_TLS_CA_FILE:$CI_SERVER_TLS_CA_FILE' -e 'GIT_SSL_CAPATH=$CI_SERVER_TLS_CA_FILE'"
  variables:
    ROS_DISTRO: "kinetic"
    UPSTREAM_WORKSPACE: "file"
    ROSINSTALL_FILENAME: ".rosinstall"
    DOCKER_BASE_IMAGE: "ros:kinetic-ros-base" # Otherwise apt fails with a 503 fetching gcc-defaults things
    ROS_REPO: "ros"

```

GIT_SSL_CAPATH does not show up in the `env` output but `CI_SERVER_TLS_CA_FILE=/builds/jkolb/ros_pkg_b.tmp/CI_SERVER_TLS_CA_FILE`

The build fails with

> Function 'prepare_docker_image' returned with code '0' after 6 min 39 sec
> Error response from daemon: create '/builds/jkolb/ros_pkg_b.tmp/CI_SERVER_TLS_CA_FILE: "'/builds/jkolb/ros_pkg_b.tmp/CI_SERVER_TLS_CA_FILE" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path
> ERROR: Job failed: exit code 1
