### ISSUE TITLE
gitlab example code fails on gitlab with shell executor

### ISSUE THREAD

**Issue by tylerjw** [ros-industrial/industrial_ci#445]
I tried using the example `.gitlab-ci.yml` from the README.md and it is failing due to `apk` missing:

```bash
bash: line 90: apk: command not found
```

Here is my config (copied from README.md):

```yml
image: docker:git
services:
  - docker:dind
before_script:
  - apk add --update bash coreutils tar
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci .industrial_ci
melodic:
  script: .industrial_ci/gitlab.sh ROS_DISTRO=melodic
```

**Comment by tylerjw** [comment]
This is because it is running as the Shell executor.  I just need to figure out how to get it to run with the docker executor.  Leaving this here in case others have this issue.

**Comment by ipa-mdl** [comment]
> This is because it is running as the Shell executor.

In principle, it should work with the shell executor as well (if you have Docker installed).
It might just work by removing that `apk` line.

**Comment by tylerjw** [comment]
@ipa-mdl It doesn't work by just removing the apk line.  It fails with this error:

```bash
SSH auto set-up cannot be used in non-disposable environments
```

**Comment by ipa-mdl** [comment]
> SSH auto set-up cannot be used in non-disposable environments

This gets printed because you have specified `SSH_PRIVATE_KEY`, which is only needed (and therefore supported) for the docker executor.
If you really need to setup SSH keys, try this: https://docs.gitlab.com/ee/ci/ssh_keys/#ssh-keys-when-using-the-shell-executor

**Comment by tylerjw** [comment]
That did work.  I first took the tactic of trying to get a docker executor and then the system person managing the infrastructure objected because that executor requires escalated privileges to run.  How have you navigated the security concerns of the docker executor?

**Comment by tylerjw** [comment]
Also, I'm now getting a failure about missing packages that should be gotten by wstool from the rosinstall.  I updated the variable `ROSINSTALL_FILENAME` but it is still failing.

**Comment by ipa-mdl** [comment]
> I updated the variable ROSINSTALL_FILENAME but it is still failing.

Did you set `UPSTREAM_WORKSPACE=file` (literal!) as well?
In general, I would recommend to use the `master` branch, in which you can set the filename directly: `UPSTREAM_WORKSPACE=my_repo.rosinstall`

**Comment by tylerjw** [comment]
I'm confused by what you are suggesting.  I tried setting that variable and read the code around how wstool is used and am confused why it isn't working.  Here is my `.gitlab-ci.yml`:

```yml
image: docker:git
services:
  - docker:dind
before_script:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci .industrial_ci
melodic:
  script:
    - export UPSTREAM_WORKSPACE=my_project.rosinstall
    - export ROSINSTALL_FILENAME=my_project.rosinstall
    - .industrial_ci/gitlab.sh ROS_DISTRO=melodic
```
