### ISSUE TITLE
Private Customer Docker Images with Bitbucket CI

### ISSUE THREAD

**Issue by tianshiz** [ros-industrial/industrial_ci#479]
I'm trying to use a custom docker image(uploaded to docker hub) with ros and all my dependencies pre-installed with ROS industrial CI. The following is my bitbucket pipelines. I've set the ENV DOCKER_IMAGE to "username\repo" and now it does pull the repo. However, I would like to make my repo private. How can I assign credentials or access tokens?

```
image: docker:git
    pipelines:
      default:
         - step:
             services:
               - docker
             caches:
               - docker
             script:
               - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci .industrial_ci -b master
               - .industrial_ci/bitbucket.sh ROS_DISTRO=kinetic

definitions:
  services:
    docker:
      memory: 2048
```
