### ISSUE TITLE
clang-format test failing saying the mode has change on two files

### ISSUE THREAD

**Issue by tylerjw** [ros-industrial/industrial_ci#529]
The diff on two files are reporting the mode has changed:

```bash
diff --git a/tmp/tmp.lmTSJ0HQ8Y/moveit/moveit_ros/visualization/rviz_plugin_render_tools/src/octomap_render.cpp b/-
old mode 100755
new mode 100644
index 07d5868..0000000
...
diff --git a/tmp/tmp.lmTSJ0HQ8Y/moveit/moveit_ros/warehouse/warehouse/src/import_from_text.cpp b/-
old mode 100755
new mode 100644
index 944d5e9..0000000
```

This seems really odd as it looks like it is clearing the executable bit somehow.  Here is the ci run where this is reproduced: https://travis-ci.com/github/ros-planning/moveit/jobs/347336919

For reference this is the .travis.yml file (the important parts to this test):
```yml
# This config file for Travis CI utilizes https://github.com/ros-industrial/industrial_ci/tree/master/ package.
os: linux
dist: xenial  # distro used by Travis, moveit_ci uses the docker image's distro
services:
  - docker
language: generic
cache: ccache
compiler: gcc

notifications:
  email: true

env:
  global:
    - ROS_DISTRO=melodic
    - ROS_REPO=ros
    - DOCKER_IMAGE=moveit/moveit:melodic-ci
    - DOCKER_BASE_IMAGE="moveit/moveit:master-ci"
    - IMMEDIATE_TEST_OUTPUT=true
    - CCACHE_DIR=$HOME/.ccache
    - BEFORE_INIT=".ci/apt_utils_setup.sh"
    - UPSTREAM_WORKSPACE=moveit.rosinstall
    - TARGET_CMAKE_ARGS='-DCMAKE_CXX_FLAGS="-Wall -Wextra -Wwrite-strings -Wunreachable-code -Wpointer-arith -Wredundant-decls" -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS_RELEASE="-O3"'

jobs:
  fast_finish: true
  include:
    - env:
      - CLANG_FORMAT_CHECK=file
      - CLANG_FORMAT_VERSION=3.9
      - CATKIN_LINT=pedantic

install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci -b master

script:
  - .industrial_ci/travis.sh
```
