### ISSUE TITLE
ccache directory not mounted in Gitlab docker:dind

### ISSUE THREAD

**Issue by Briancbn** [ros-industrial/industrial_ci#536]
Here is my .gitlab-ci.yml
```yml
image: docker:git
services:
  - docker:dind
before_script:
  - apk add --update bash coreutils tar curl ccache
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci .industrial_ci -b master
  - mkdir -p $HOME/.ccache/
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths: 
    - $HOME/.ccache/

variables:
  CCACHE_DIR: "$HOME/.ccache"
  DOCKER_DRIVER: overlay2

dashing-main:
  script: .industrial_ci/gitlab.sh ROS_DISTRO=dashing ROS_REPO=main AFTER_SCRIPT="ccache -s"

dashing-testing:
  script: .industrial_ci/gitlab.sh ROS_DISTRO=dashing ROS_REPO=testing

eloquent-main:
  script: .industrial_ci/gitlab.sh ROS_DISTRO=eloquent ROS_REPO=main

eloquent-testing:
  script: .industrial_ci/gitlab.sh ROS_DISTRO=eloquent ROS_REPO=testing

after_script:
  - ls $HOME/.ccache
  - ccache -s

```
And here is the [log](https://gitlab.com/Brian97cbn/packml_ros2-gitlab/-/jobs/604649406). 
I have an after script to check the `$HOME/.ccache` folder, but it was empty.
The ccache directory is not mounted onto the path **CCACHE_DIR** specified. 
And rerun the CI pipeline won't use the correct cache to download
