### ISSUE TITLE
[SOLVED]Integration Tests Configuration

### ISSUE THREAD

**Issue by alokforros** [ros-industrial/industrial_ci#560]
I am using Industrial CI for the first time for my ROS package here : 

[https://github.com/cognicept-admin/rosrect-listener-agent/tree/travis-ci](https://github.com/cognicept-admin/rosrect-listener-agent/tree/travis-ci)

I am running some integration tests that require some rest API calls to the python-sanic server running locally. While My python server runs and I can use simple curl commands to check if its up. My API calls are otherwise failing. Any feedback and comment on my Pipeline configuration would be really helpful. 

Thanks in advance

```
sudo: required 
dist: bionic 
language: generic
branches:
  only:
  - travis-ci

cache:
  directories:
    - $HOME/.ccache

compiler:
  - gcc
notifications:
  email:
    on_failure: always

env:
  global:
   - NOT_TEST_INSTALL=true
   - CCACHE_DIR=$HOME/.ccache  
   - ECS_API=http://127.0.0.1:8000
   - AGENT_POST_API=https://postman-echo.com
   - ECS_DB_LOC=rosrect-ecs-api-server/ecs.db
  matrix:
    - USE_DEB=true  
      ROS_DISTRO="melodic" 
      ROS_REPO=ros
      ADDITIONAL_DEBS="libcpprest-dev curl"
      CMAKE_ARGS="-DENABLE_COVERAGE_TESTING=ON -DCMAKE_BUILD_TYPE=Debug"

allow_failures:
    - env: ROS_DISTRO="melodic" ROS_REPO=ros  ADDITIONAL_DEBS="libcpprest-dev"

before_install:
  #installing microsoft libcpprest dependency
  - sudo apt-get install libcpprest-dev
  - pip install --user cpp-coveralls

install:
  - git clone https://github.com/cognicept-admin/rosrect-ecs-api-server.git  
  - git clone https://github.com/ros-industrial/industrial_ci.git .industrial_ci -b master

before_script:
  - sudo apt-get update
  - sudo apt-get install python3-pip
  - sudo apt-get install python3-setuptools
  - sudo apt install gcovr
  - pip3 install sanic
  - pip3 install databases
  - pip3 install aiosqlite
  - export ECS_API=http://127.0.0.1:8000
  - export AGENT_POST_API=https://postman-echo.com
  - export ECS_DB_LOC=rosrect-ecs-api-server/ecs.db
  - chmod +x ci-test.sh
  - ./ci-test.sh
  - sleep 10

script:
  - curl 'http://127.0.0.1:8000/ping'
  - source .industrial_ci/travis.sh
  - gcovr -r . --exclude-directories test
  - curl 'http://127.0.0.1:8000/ping'


after_success:
  - coveralls --gcov-options '\-lp'
```

The error that I get is listed here : 
[https://travis-ci.org/github/cognicept-admin/rosrect-listener-agent/builds/729235575](https://travis-ci.org/github/cognicept-admin/rosrect-listener-agent/builds/729235575)

Specifically,  : 
```
ECS API error: Failed to connect to any resolved endpoint. Agent will retry API connection at: http://0.0.0.0:8000/ert/error-data/
```
