### ISSUE TITLE
Update Github Action template

### ISSUE THREAD

**Issue by ipa-mdl** [ros-industrial/industrial_ci#590]
The current matrix expansion approach works, but it is not the intended usage and results in a warning.

![image](https://user-images.githubusercontent.com/727227/105580320-f825db80-5d8b-11eb-90bf-923ebb48f8f3.png)
> Matrix options must only contain primitive values

**Comment by gavanderhoorn** [comment]
This should be equivalent:

```yaml
jobs:
  industrial_ci:
    strategy:
      matrix:
        ros_distro: [ melodic ]
        ros_repo: [ main, testing ]

    ...

    steps:
      - ...

      - uses: ros-industrial/industrial_ci@master
        env:
          ROS_DISTRO: ${{ matrix.ros_distro }}
          ROS_REPO: ${{ matrix.ros_repo }}

      - ...
```

I haven't really found a way yet to provide 'defaults' in the `matrix` section.

Could set `env.ROS_REPO` to `main` perhaps and then rely on the `matrix` expansion to override it when desired?

**Comment by ipa-mdl** [comment]
Yes, this is what I had in mind.
I just don't like the redundancy..

We could extend the action to read the matrix variable and then deal with  the defaults (from `env.*`).

**Comment by ipa-mdl** [comment]
@gavanderhoorn: 

How do you like this option (#591)?
```yaml
jobs:
  industrial_ci:
    strategy:
      matrix:
        ROS_DISTRP: [ melodic ]
        ROS_REPO: [ main, testing ]

    ...

    steps:
      - ...

      - uses: ros-industrial/industrial_ci@master
        with
          matrix: ${{ toJSON(matrix) }}        
      - ...
```

**Comment by gavanderhoorn** [comment]
Hm.

I actually liked the fact you have to explicitly tell each step (and in this case the `industrial_ci` step) where the values come from.

It's *really* obvious reading the `.yml` that step gets two env vars: `ROS_DISTRO` and `ROS_REPO`, and their values come from the `matrix` stanza earlier in the file.

With your proposal, you have to understand how `toJSON(..)` works and what gets passed exactly.

That's of course OK, but if we can get something equivalent (and I believe the default way to do this is) and it's easier to grok, it may be preferable over saving a line (or two, or three ..).

Do we expect the `matrix` to contain *lots* of variables / options? If yes: then your proposal would avoid significant duplication. If average configurations will only have a few rows in the `matrix`, and the rest of the env vars specified either globally or on the `industrial_ci` step itself, then perhaps having things explicitly mapped (ie: as in https://github.com/ros-industrial/industrial_ci/issues/590#issuecomment-766094455) might not be so bad.

**Comment by ipa-mdl** [comment]
> I actually liked the fact you have to explicitly tell each step (and in this case the industrial_ci step) where the values come from.

You can still do this:
```yaml
jobs:
  industrial_ci:
    strategy:
      matrix:
        include:
          - { ROS_DISTRO: melodic }
          - { ROS_DISTRO: melodic, ROS_REPO: main }

    ...

    steps:
      - ...

      - uses: ros-industrial/industrial_ci@master
        with
          matrix: ${{ toJSON(matrix) }}        
      - ...
```

Or even a mix of both. And the `env` hack still works.

> It's really obvious reading the .yml that step gets two env vars: ROS_DISTRO and ROS_REPO, and their values come from the matrix stanza earlier in the file.

The `env` hack in the current template is a not supported/intended use case (by Github Actions).
They might reject this configuration in the future. (Or support it..).

My intention was to support `env` overiding as well:

```yaml
      - uses: ros-industrial/industrial_ci@master
        with
          matrix: ${{ toJSON(matrix) }}
        env:
           CCACHE_DIR: ...
```

> With your proposal, you have to understand how toJSON(..) works and what gets passed exactly.

It would be great to avoid `toJSON`, but the action fails somewhere in the middle because of some validation check.
Again, this is optional, just for actual matrix operations.
