### ISSUE TITLE
[gha] pull_docker_image fails with latest master

### ISSUE THREAD

**Issue by fmessmer** [ros-industrial/industrial_ci#610]
we have been using our own docker image in github actions with our ici branch pinned to https://github.com/ros-industrial/industrial_ci/commit/db261d7d667ead4e7870b5149c178efda313dd77 (+ pylint feature from #477, i.e.  https://github.com/fmessmer/industrial_ci/tree/master_pylint)

the config is (ref https://github.com/ros-industrial/industrial_ci/issues/574):
```
name: CI

on:
  push:
  pull_request:

jobs:
  industrial_ci:
    timeout-minutes: 60
    env:
      ADDITIONAL_DEBS: 'apt-utils curl dialog git-core openssh-client openssh-server wget'
      AFTER_INIT: mkdir -p ~/.ssh && touch ~/.ssh/known_hosts && ssh-keyscan github.com >> ~/.ssh/known_hosts && git config --global url."https://token:${{secrets.GITHUBPAT}}@github.com/".insteadOf "git@github.com:" && curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash && apt-get install git-lfs -y && cd $HOME && git lfs install && cd -
      BEFORE_PREPARE_DOCKER_IMAGE: echo ${{secrets.GITHUBPAT}} | docker login ghcr.io -u mojin-robotics-ci --password-stdin
      CATKIN_LINT: pedantic
      CATKIN_LINT_ARGS: '--ignore description_boilerplate --ignore target_name_collision'
      CMAKE_ARGS: -DCMAKE_BUILD_TYPE=Release
      NOT_TEST_DOWNSTREAM: true
      PYLINT_ARGS: "--output-format=parseable --errors-only"
      PYLINT2_CHECK: true  # pylint2 for kinetic, pylint3 for noetic
      PYLINT3_CHECK: false
      ROS_REPO: main
      SECRET_AVAILABLE: ${{secrets.GITHUBPAT}}
      VERBOSE_OUTPUT: false
      VERBOSE_TESTS: false
    strategy:
      matrix:
        env:
          - { ROS_DISTRO: kinetic,
              DOCKER_IMAGE: 'ghcr.io/mojin-robotics/mojin-ros:kinetic-full'
            }
          - { ROS_DISTRO: noetic,
              DOCKER_IMAGE: 'ghcr.io/mojin-robotics/mojin-ros:noetic-full'
            }
    name: ${{matrix.env.ROS_DISTRO}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - uses: 'fmessmer/industrial_ci@master_pylint'
        if: ${{ env.SECRET_AVAILABLE }} # prevents failure notifications if secret GITHUBPAT is not available
        env: ${{matrix.env}}
```

I rebased my `fmessmer/industrial_ci@master_pylint` branch to latest `ros-industrial/industrial_ci@master` branch to get the latest features, but with latest `ros-industrial/industrial_ci@master` we cannot pull our docker image anymore:
```
  Starting function 'pull_docker_image'
  Error response from daemon: Get https://ghcr.io/v2/mojin-robotics/mojin-ros/manifests/kinetic-full: unauthorized
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
Function 'pull_docker_image' returned with code '1' after 0 min 1 sec
Error: Process completed with exit code 1.
```

I quickly investigated what has changed since https://github.com/ros-industrial/industrial_ci/commit/db261d7d667ead4e7870b5149c178efda313dd77, but could not find an obvious solution
