### ISSUE TITLE
Provide feedback on outcome of individual steps

### ISSUE THREAD

**Issue by rhaschke** [ros-industrial/industrial_ci#753]
To automate various actions in GHA depending on the outcome of steps in `industrial_ci`, it would be great to have the exit code of individual steps as [output feedback](https://docs.github.com/en/actions/learn-github-actions/workflow-commands-for-github-actions#setting-an-output-parameter).

```yaml
steps:
  - id: industrial_ci
    uses: ros-industrial/industrial_ci@master
  - name: Upload test artifacts (on test failure)
     uses: actions/upload-artifact@v2
     if: steps.industrial_ci.outputs.run_target_test != 0
     with:
          name: test-results
          path: ${{ env.BASEDIR }}/target_ws/**/test_results/**/*.xml
```
