### ISSUE TITLE
Industrial CI failure 

### ISSUE THREAD

**Issue by nocoinman** [ros-industrial/industrial_ci#761]
Config file
---

```yaml
name: lint

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  - push
  - pull_request

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - ROS_DISTRO: noetic
            CLANG_FORMAT_CHECK: file
            CLANG_FORMAT_VERSION: 11

          - OS_CODE_NAME: focal
            BLACK_CHECK: true

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
```

Output on failure
---

```bash
$ sudo apt-get -qq install -y --no-upgrade --no-install-recommends apt-utils build-essential gnupg2 dirmngr ca-certificates | grep -E 'Setting up' 
  Setting up gnupg2 (2.2.27-2) ...
  Setting up apt-utils (2.2.4) ...
  Setting up build-essential (12.9) ...
  Using default ROS_REPO=testing
  /home/runner/work/_actions/ros-industrial/industrial_ci/master/industrial_ci/src/ros.sh: line 124: ROS_VERSION: unbound variable
  /home/runner/work/_actions/ros-industrial/industrial_ci/master/industrial_ci/src/ros.sh: line 108: ROS_VERSION_EOL: unbound variable
  industrial_ci terminated unexpectedly with exit code '1'
  
  TRACE:ros.sh:1 ici_trap_exit 
     AT:ros.sh:162 _use_repo_or_final_snapshot
     AT:workspace.sh:145 ici_set_ros_repository_path
     AT:util.sh:213 ici_init_apt
     AT:run.sh:61 ici_step
'init' returned with code '143' after 0 min 9 sec
```

Pipelines were running fine until today. Changes since commit de433461b9c2c40e71e9eceae43fb8e195395a64 **might** be the cause.
