### ISSUE TITLE
Submodules of repository get not cloned

### ISSUE THREAD

**Issue by repa1030** [ros-industrial/industrial_ci#784]
Hi,

I have established the pipeline in a gitlab project but I have submodules in my repository and those get skipped everytime:
_"Skipping Git submodules setup"_
And therefore they are not build and my pipeline fails.
Is there a variable that has to be set for git submodules to be initialized and cloned?

Here is my minimalistic CI config file:
```
image: docker:git

services:
  - docker:dind

before_script:
  - apk add --update bash coreutils tar
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci .industrial_ci -b master

# Distro pipelines
melodic:
  script: .industrial_ci/gitlab.sh
  variables:
    BUILDER: "catkin_tools"
    ROS_DISTRO: "melodic"

noetic:
  script: .industrial_ci/gitlab.sh
  variables:
    BUILDER: "catkin_tools"
    ROS_DISTRO: "noetic"
```

Thank you for your answer.
