### ISSUE TITLE
Setting github output for failed `colcon test-result` broken

### ISSUE THREAD

**Issue by fmauch** [ros-industrial/industrial_ci#853]
Hi,

after debugging a bit it seems to me that output reporting for a failed `colcon test-result` is broken.

I have setup a [minimal project](https://github.com/fmauch/simple_package) with a small C++-"library" and a gtest.

In the [workflow](https://github.com/fmauch/simple_package/blob/ce6f6cf173c86abec560dea9eabf07fd632fc898/.github/workflows/ici.yml#L23-L30) I run ICI and print some ici outputs:
```yaml
      - uses: 'ros-industrial/industrial_ci@master'
        env:
          ROS_DISTRO: ${{ matrix.ROS_DISTRO }}
          ROS_REPO: ${{ matrix.ROS_REPO }}
        id: ici
      - name: Print ICI outputs
        if: ${{ always() }}
        run: echo 'build_target_workspace is ${{ steps.ici.outputs.build_target_workspace }}, run_target_test is ${{ steps.ici.outputs.run_target_test }}, target_test_results is ${{ steps.ici.outputs.target_test_results }}'
```

When everything succeeds, this prints
```
build_target_workspace is 0, run_target_test is 0, target_test_results is 0
```

However, when I add a deliberate failure to the gtest the [result](https://github.com/fmauch/simple_package/actions/runs/8319027481/job/22761727148#step:4:5) is
```
build_target_workspace is 0, run_target_test is 0, target_test_results is 
```

I verified that running [the same commands](https://github.com/ros-industrial/industrial_ci/blob/6931750a64c88d171e23b5397c6c14231acc27cd/industrial_ci/src/workspace.sh#L402-L403) (stripped by ici wrapping) locally
```
err=0
colcon test
colcon test-result --verbose || err=$?
echo "Test result: $err"
```

prints `Test result: 1` in the end so I'm not sure whats going on here.
