### ISSUE TITLE
Add colcon arguments for selecting packages to build

### ISSUE THREAD

**Issue by rafal-gorecki** [ros-industrial/industrial_ci#859]
Hello,
1. I'm looking for some solutions: to add option `--packages-up-to <package_name>` during the colcon build and test phase. How can be it done on Github Actions?
2. I'd like to also add global environment variable, how can I add it? I try following solutions, but it didn't work:
```yaml
      - uses: ros-industrial/industrial_ci@master
        env:
          ROS_DISTRO: ${{matrix.ROS_DISTRO}}
          global:
            - BEFORE_INIT='export HUSARION_ROS_BUILD_TYPE=simulation'
```
Regards
