### ISSUE TITLE
Bitbucket  "authorization denied" --> API call limitation?

### ISSUE THREAD

**Issue by AndyZe** [ros-industrial/industrial_ci#882]
On Sep 17 I started experiencing this issue on my bitbucket pipelines:

```
time="2024-09-18T19:00:50.149245108Z" level=error msg="AuthZRequest for HEAD /_ping returned error: authorization denied by plugin pipelines: "
```

I guess it's probably not a coincidence that bitbucket deprecated legacy pipelines on Sep 17.

There are some solutions described [here](https://community.atlassian.com/t5/Bitbucket-questions/Docker-build-failing-for-buildkit-with-error-authorization/qaq-p/2377667#M94515)

Basically it sounds like this is deprecated:  `DOCKER_BUILDKIT=0`

Maybe the new way to do it is:  `export PATH=/usr/bin:$PATH`

Here's my `bitbucket-pipelines.yml` with the fix I attempted. It didn't work.

```
image: docker:git

pipelines:
  default:
     - step:
         services:
           - docker
         script:
           # Attempted fix
           # See https://community.atlassian.com/t5/Bitbucket-questions/Docker-build-failing-for-buildkit-with-error-authorization/qaq-p/2377667#M94515
           - export PATH=/usr/bin:$PATH
           - apk add --update bash coreutils tar
           - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci .industrial_ci -b master
           - .industrial_ci/bitbucket.sh ROS_DISTRO=humble

definitions:
  services:
    docker:
      memory: 2048
```

**Comment by mathias-luedtke** [comment]
Thanks for reporting!

 > time="2024-09-18T19:00:50.149245108Z" level=error msg="AuthZRequest for HEAD /_ping returned error: authorization denied by plugin pipelines: "

Could you give me a little bit more context, please?
This looks like the "docker pull" fails or gets blocked.
You could set `TRACE=true` as well, which should print all the internal industrial_ci commands, which should help to narrow the scope.

> Basically it sounds like this is deprecated: DOCKER_BUILDKIT=0

This has been deprecated (by docker) for a while now.
And it does not matter, because industrial_ci does not build any docker images. It just runs them.

> Maybe the new way to do it is: export PATH=/usr/bin:$PATH

I would not mess with $PATH unless there is a good reason to do that.
To debug that more: Could you add an `env` call to your script and see what is the default for PATH.
And does bitbucket set any DOCKER_* environment variables?

**Comment by mathias-luedtke** [comment]
According to https://support.atlassian.com/bitbucket-cloud/docs/run-docker-commands-in-bitbucket-pipelines/ running docker containers should be a supported use case.
`image: docker:git`  is not listed in any of the examples, though.

And it looks like bitbucket restricts the locations that can be mounted via volumes.
Please try setting `DOCKER_CREDENTIALS=""`. This should disable the extra-mounts, but as well the option to clone other repos.

If Docker does work anymore, there is as well the `ISOLATION=shell `option:
https://github.com/ros-industrial/industrial_ci/blob/master/.gitlab-ci.yml#L39

**Comment by AndyZe** [comment]
I added this stuff to bitbucket-pipelines.yml. Didn't seem to change anything, though-

```

**Comment by AndyZe** [comment]
Adding `export ISOLATION=shell` really screws things up:

```
image: docker:git
pipelines:
  default:
     - step:
         size: 2x # More memory
         services:
           - docker
         script:
           - export TRACE=true
           - env
           - export DOCKER_CREDENTIALS=""
           - export ISOLATION=shell
           - git clone git@bitbucket.org:apptronik/elevate_robotics.git
           - apk add --update bash coreutils tar
           - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci .industrial_ci -b master
           - .industrial_ci/bitbucket.sh ROS_DISTRO=humble
definitions:
  services:
    docker:
      memory: 4096
```
-->

```
TRACE:util.sh:533 ici_guard source /opt/atlassian/pipelines/agent/build/.industrial_ci/industrial_ci/src/tests/source_tests.sh
TRACE:util.sh:163 ici_hook before_init
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
init
/opt/atlassian/pipelines/agent/build/.industrial_ci/industrial_ci/src/util.sh: line 466: debconf-set-selections: command not found
$ sudo sed -i /^# deb.*multiverse/ s/^# // /etc/apt/sources.list
sed: /etc/apt/sources.list: No such file or directory
'sudo sed -i /^# deb.*multiverse/ s/^# // /etc/apt/sources.list' returned with 1
TRACE:util.sh:316 ici_exit 1
   AT:util.sh:442 ici_error
   AT:util.sh:459 _ici_guard
   AT:workspace.sh:116 ici_cmd
   AT:util.sh:214 ici_init_apt
   AT:run.sh:61 ici_step
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
'init' returned with code '1' after 0 min 0 sec
TRACE:util.sh:208 ici_hook after_init
TRACE:ci_main.sh:75 ici_exit 
```
