### ISSUE TITLE
Bitbucket: if CLANG_FORMAT_CHECK is enabled, tests don't run

### ISSUE THREAD

**Issue by AndyZe** [ros-industrial/industrial_ci#889]
I've done `export CLANG_FORMAT_CHECK="file"` and that seems to work well. However, my other gtests do not run now. Only `clang-format` runs. Here's my config file, edited to hide some proprietary info:

```
pipelines:
  default:
     - step:
         size: 2x # More memory
         services:
           - docker
         script:
           - export DOCKER_IMAGE="ros:humble"
# When CLANG_FORMAT_CHECK is present, gtests don't run
           - export CLANG_FORMAT_CHECK="file"
           - export CLANG_FORMAT_VERSION="14"
           - export CLANG_TIDY="true"
           - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci .industrial_ci -b master
           - .industrial_ci/bitbucket.sh ROS_DISTRO=humble
definitions:
  services:
    docker:
      memory: 7100
```

**Comment by AndyZe** [comment]
Resolved by creating multiple steps:

```
pipelines:
  default:
    # Basic CI
    - step:
        size: 2x # More memory
        services:
          - docker
        script:
          - export DOCKER_IMAGE="ros:humble"
          - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci .industrial_ci -b master
          - .industrial_ci/bitbucket.sh ROS_DISTRO=humble
    # Clang format
    - step:
        size: 2x # More memory
        services:
          - docker
        script:
          - export DOCKER_IMAGE="ros:humble"
          - export CLANG_FORMAT_CHECK="file"
          - export CLANG_FORMAT_VERSION="14"
          - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci .industrial_ci -b master
          - .industrial_ci/bitbucket.sh ROS_DISTRO=humble
definitions:
  services:
    docker:
      memory: 7100
```
