### ISSUE TITLE
How to run additional steps in the same environment

### ISSUE THREAD

**Issue by firesurfer** [ros-industrial/industrial_ci#901]
Hi I am currently using the industrial_ci successfully in our github ci pipeline. 
Now I would like to add additional steps that are run in the same environment. In this specific case I would like to run xacro on our urdf.xacro files in order to test if certain configuration can be processed successfully. 

What I tried so far:

1.  Add an additional step after:

```
      - uses: 'ros-industrial/industrial_ci@master'
        env:
          UPSTREAM_WORKSPACE: ${{ inputs.upstream_workspace }}
          ROS_DISTRO: ${{ inputs.ros_distro }}
          ROS_REPO: ${{ inputs.ros_repo }}
      - name: Xacro
        run: |
            xacro <path to xacro file>
```

2. Use the AFTER_SCRIPT to run the same command

In both cases it looks like the command is not run in the same environment as the one the industrial_ci pipeline runs in. (command xacro not found)

So the question is:
How can I run a custom command in the same environment after the build has finished?
